export const dataBreeds = {
    "perros": [
        { "tipo": "Perro", "nombre": "Labrador Retriever" },
        { "tipo": "Perro", "nombre": "Pastor Alemán" },
        { "tipo": "Perro", "nombre": "Golden Retriever" },
        { "tipo": "Perro", "nombre": "Bulldog Francés" },
        { "tipo": "Perro", "nombre": "Bulldog Inglés" },
        { "tipo": "Perro", "nombre": "Beagle" },
        { "tipo": "Perro", "nombre": "Caniche" },
        { "tipo": "Perro", "nombre": "Boxer" },
        { "tipo": "Perro", "nombre": "Dálmata" },
        { "tipo": "Perro", "nombre": "Chihuahua" },
        { "tipo": "Perro", "nombre": "Yorkshire Terrier" },
        { "tipo": "Perro", "nombre": "Poodle" },
        { "tipo": "Perro", "nombre": "Shih Tzu" },
        { "tipo": "Perro", "nombre": "Husky Siberiano" },
        { "tipo": "Perro", "nombre": "Pomerania" },
        { "tipo": "Perro", "nombre": "Rottweiler" },
        { "tipo": "Perro", "nombre": "Doberman" },
        { "tipo": "Perro", "nombre": "Border Collie" },
        { "tipo": "Perro", "nombre": "Bóxer" },
        { "tipo": "Perro", "nombre": "Basset Hound" },
        { "tipo": "Perro", "nombre": "Bichón Maltés" },
        { "tipo": "Perro", "nombre": "Pointer" },
        { "tipo": "Perro", "nombre": "Bull Terrier" },
        { "tipo": "Perro", "nombre": "Shiba Inu" },
        { "tipo": "Perro", "nombre": "Schnauzer" },
        { "tipo": "Perro", "nombre": "Gran Danés" },
        { "tipo": "Perro", "nombre": "Borzoi" },
        { "tipo": "Perro", "nombre": "Akita" },
        { "tipo": "Perro", "nombre": "Galgo" },
        { "tipo": "Perro", "nombre": "Cocker Spaniel" },
        { "tipo": "Perro", "nombre": "Setter Irlandés" }
    ],
    "gatos": [
        { "tipo": "Gato", "nombre": "Siamés" },
        { "tipo": "Gato", "nombre": "Persa" },
        { "tipo": "Gato", "nombre": "Maine Coon" },
        { "tipo": "Gato", "nombre": "Ragdoll" },
        { "tipo": "Gato", "nombre": "Bengalí" },
        { "tipo": "Gato", "nombre": "Sphynx" },
        { "tipo": "Gato", "nombre": "British Shorthair" },
        { "tipo": "Gato", "nombre": "Ruso Azul" },
        { "tipo": "Gato", "nombre": "Siberiano" },
        { "tipo": "Gato", "nombre": "Exótico" },
        { "tipo": "Gato", "nombre": "Abisinio" },
        { "tipo": "Gato", "nombre": "Burmés" },
        { "tipo": "Gato", "nombre": "Cornish Rex" },
        { "tipo": "Gato", "nombre": "Tonkinés" },
        { "tipo": "Gato", "nombre": "American Curl" },
        { "tipo": "Gato", "nombre": "Devon Rex" },
        { "tipo": "Gato", "nombre": "Sagrado de Birmania" },
        { "tipo": "Gato", "nombre": "Bombay" },
        { "tipo": "Gato", "nombre": "Somalí" },
        { "tipo": "Gato", "nombre": "Manx" },
        { "tipo": "Gato", "nombre": "Singapura" },
        { "tipo": "Gato", "nombre": "Scottish Fold" },
        { "tipo": "Gato", "nombre": "Noruego del Bosque" },
        { "tipo": "Gato", "nombre": "Turco Van" },
        { "tipo": "Gato", "nombre": "Angora Turco" },
        { "tipo": "Gato", "nombre": "Toyger" },
        { "tipo": "Gato", "nombre": "Selkirk Rex" },
        { "tipo": "Gato", "nombre": "Khao Manee" },
        { "tipo": "Gato", "nombre": "Himalayo" },
        { "tipo": "Gato", "nombre": "Manés" },
        { "tipo": "Gato", "nombre": "Bobtail Japonés" }
    ]
};
